[package]
name = "protoc-gen-mdbook"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
askama = "0"
bytes = "1"
prost = "0.11"
prost-types = "0.11"

[profile.release]
strip = "debuginfo"
lto = "fat"
