[package]
name = "protoc-gen-mdbook"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
askama = { version = "0", default-features = false }
bytes = "1"
prost = "0.12"
prost-types = "0.12"
regex = "1"

[profile.release]
strip = "debuginfo"
lto = "fat"
